services:

  ollama:
    build:
      context: ./ollama

    container_name: careersphere-ollama

    ports:
      - "11434:11434"

    volumes:
      - ollama_data:/root/.ollama

    environment:
      - OLLAMA_HOST=0.0.0.0:11434

    restart: unless-stopped


volumes:
  ollama_data: